### ISSUE TITLE
UnknownHostException-Fluentd

### ISSUE THREAD

**Issue by harishkadamudi** [monkey-codes/spring-boot-restful#1]
I followed your instruction to run the application, but received exception stated below.
I understand by below exception that, i need to configure fluentd.

java.net.UnknownHostException: fluentd
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_102]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_102]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_102]
    at org.fluentd.logger.sender.RawSocketSender.connect(RawSocketSender.java:83) [fluent-logger-0.3.2.jar!/:na]
    at org.fluentd.logger.sender.RawSocketSender.reconnect(RawSocketSender.java:92) [fluent-logger-0.3.2.jar!/:na]
    at org.fluentd.logger.sender.RawSocketSender.flush(RawSocketSender.java:186) [fluent-logger-0.3.2.jar!/:na]
    at org.fluentd.logger.sender.RawSocketSender.send(RawSocketSender.java:177) [fluent-logger-0.3.2.jar!/:na]
    at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:147) [fluent-logger-0.3.2.jar!/:na]
    at org.fluentd.logger.sender.RawSocketSender.emit(RawSocketSender.java:129) [fluent-logger-0.3.2.jar!/:na]
    at org.fluentd.logger.FluentLogger.log(FluentLogger.java:99) [fluent-logger-0.3.2.jar!/:na]
    at ch.qos.logback.more.appenders.DataFluentAppender$FluentDaemonAppender.append(DataFluentAppender.java:95) [logback-more-appenders-1.1.0.jar!/:na]
    at ch.qos.logback.more.appenders.DataFluentAppender$FluentDaemonAppender.append(DataFluentAppender.java:41) [logback-more-appenders-1.1.0.jar!/:na]
    at ch.qos.logback.more.appenders.DaemonAppender.run(DaemonAppender.java:65) [logback-more-appenders-1.1.0.jar!/:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by monkey-codes** [comment]
I have updated the readme (https://github.com/monkey-codes/spring-boot-restful) with instructions on how to run the sample code. I did notice during the build one of the tests will log the UnkownhostException, you can safely ignore this exception during the build.
